language: php

php:
    - 7.2
    - 7.3
    - 7.4

before_install:
    - composer self-update
    - composer --version
    - wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer.phar;
    - php php-cs-fixer.phar --version
    - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.2/php-coveralls.phar

install:
    - COMPOSER_ROOT_VERSION=dev-master composer update --prefer-source $COMPOSER_FLAGS

script:
    - php php-cs-fixer.phar fix --dry-run -v
    - bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then php php-coveralls.phar -v; fi
